name: CI

permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: ''

      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b

      - name: Install GoMobile
        run: go install golang.org/x/mobile/cmd/gomobile@latest

      - name: Build GoMobile AAR
        run: |
          go get golang.org/x/mobile/bind
          gomobile init
          cd bindings
          gomobile bind -target=android -androidapi 23 -ldflags "-s -w" -o ../torrserver.aar

      - name: Upload AAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: torrserver-aar
          path: torrserver.aar
          if-no-files-found: error
